server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/store
    username: root
    password: 3221
mybatis-plus:
  mapper-locations: com/storeapp/mapper/xml/*.xml